---
name: Gradle

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [11, 17, 21]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_commands: --stacktrace build
      ArtifactoryUserName: ${{ secrets.JENKINS_USERNAME }}
      ArtifactoryPassword: ${{ secrets.JENKINS_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Run commands
        run: |
          ./gradlew ${{ env.gradle_commands }}
      - name: Publish artifacts
        if: github.event_name != 'pull_request' && matrix.java == 11
        run: |
          ./gradlew -PArtifactoryUserName=${ArtifactoryUserName} -PArtifactoryPassword=${ArtifactoryPassword} publish
